# Generated by Django 4.2 on 2023-04-09 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('cpf', models.CharField(max_length=30)),
                ('rg', models.CharField(max_length=30)),
                ('sexo', models.CharField(choices=[('Masulino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], max_length=30)),
                ('data_nascimento', models.DateField()),
                ('habilitacao', models.BooleanField()),
                ('salario', models.FloatField()),
                ('carga_horaria_semanal', models.IntegerField()),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departamento.departamento')),
            ],
            options={
                'unique_together': {('nome', 'cpf', 'rg')},
            },
        ),
    ]
